"""
Voice Cloning Quality Report

Generates a detailed speaker similarity report comparing:
  1. Reference voice audio (provided or auto-generated by the model)
  2. Cloned output — same text as target, generated with the reference voice
  3. Baseline output — same text, generated WITHOUT a voice reference

Metrics reported:
  - ECAPA-TDNN cosine similarity (speechbrain/spkrec-ecapa-voxceleb)
  - Librosa multi-feature cosine similarity (MFCC + delta + spectral + F0)
  - Ensemble score (weighted combination)

Usage:
    # Auto-generate reference voice, then clone it
    python demo/voice_clone_quality.py \\
        --model /mnt/nas/models/vibevoice/VibeVoice-1.5B \\
        --output_dir ./quality_output

    # Use an existing reference audio file
    python demo/voice_clone_quality.py \\
        --model /mnt/nas/models/vibevoice/VibeVoice-1.5B \\
        --reference_audio my_voice.wav \\
        --target_text "Speaker 0: The quick brown fox jumps over the lazy dog." \\
        --output_dir ./quality_output
"""

import argparse
import os
import sys
import json
import numpy as np
import torch

SAMPLE_RATE = 24_000

DEFAULT_REF_TEXT = (
    "Speaker 0: Good morning. This is a reference voice sample for testing "
    "the VibeVoice voice cloning system. I am speaking clearly so the model "
    "can capture the characteristics of this voice."
)
DEFAULT_TARGET_TEXT = (
    "Speaker 0: The quick brown fox jumps over the lazy dog near the riverbank "
    "on a warm sunny afternoon."
)


# ---------------------------------------------------------------------------
# Audio helpers
# ---------------------------------------------------------------------------

def load_audio(path: str) -> np.ndarray:
    """Load and normalise audio to 24 kHz mono float32."""
    import soundfile as sf
    import librosa
    wav, sr = sf.read(path, always_2d=False)
    wav = wav.astype(np.float32)
    if wav.ndim > 1:
        wav = wav.mean(axis=1)
    if sr != SAMPLE_RATE:
        wav = librosa.resample(wav, orig_sr=sr, target_sr=SAMPLE_RATE)
    return wav


def save_audio(path: str, wav: np.ndarray, sr: int = SAMPLE_RATE) -> None:
    import soundfile as sf
    sf.write(path, wav.astype(np.float32), sr)
    print(f"  Saved: {path}  ({len(wav)/sr:.1f}s)")


def tensor_to_numpy(audio) -> np.ndarray:
    if isinstance(audio, torch.Tensor):
        audio = audio.cpu().float().numpy()
    if audio.ndim > 1:
        audio = audio.mean(axis=0)
    return audio.astype(np.float32)


# ---------------------------------------------------------------------------
# Model helpers
# ---------------------------------------------------------------------------

def load_model_and_processor(model_path: str, device: str):
    from vibevoice.modular.modeling_vibevoice_inference import (
        VibeVoiceForConditionalGenerationInference,
    )
    from vibevoice.processor.vibevoice_processor import VibeVoiceProcessor

    print(f"Loading model from {model_path} ...")
    processor = VibeVoiceProcessor.from_pretrained(model_path)
    dtype = torch.bfloat16 if "cuda" in device else torch.float32
    model = VibeVoiceForConditionalGenerationInference.from_pretrained_hf(
        model_path, device=device, torch_dtype=dtype,
    )
    model.eval()
    return model, processor


def generate(model, processor, text: str, voice_samples=None,
             cfg_scale: float = 3.0, ddpm_steps: int = 20,
             device: str = "cuda") -> np.ndarray:
    model.set_ddpm_inference_steps(ddpm_steps)

    kwargs = dict(text=text, return_tensors="pt")
    if voice_samples is not None:
        kwargs["voice_samples"] = voice_samples
    inputs = processor(**kwargs).to(device)

    with torch.no_grad():
        output = model.generate(
            **inputs,
            tokenizer=processor.tokenizer,
            cfg_scale=cfg_scale,
            return_speech=True,
        )

    if output.speech_outputs and output.speech_outputs[0] is not None:
        return tensor_to_numpy(output.speech_outputs[0])
    return None


# ---------------------------------------------------------------------------
# Report formatting
# ---------------------------------------------------------------------------

def print_report(report: dict) -> None:
    sep = "-" * 60
    print(f"\n{'='*60}")
    print("  VOICE CLONING QUALITY REPORT")
    print(f"{'='*60}")
    print(f"\n  {report['summary']}")
    print(f"\n{sep}")
    print("  Reference vs Cloned (higher = more similar to reference)")
    for k, v in report["reference_vs_cloned"].items():
        bar = "#" * int(v * 40)
        print(f"    {k:<15} {v:.4f}  |{bar}")
    print(f"\n{sep}")
    print("  Reference vs Baseline (this is the baseline to beat)")
    for k, v in report["reference_vs_baseline"].items():
        bar = "#" * int(v * 40)
        print(f"    {k:<15} {v:.4f}  |{bar}")
    print(f"\n{sep}")
    print("  Delta (cloned - baseline, positive = cloning is working)")
    for k, v in report["delta"].items():
        sign = "+" if v >= 0 else ""
        print(f"    {k:<15} {sign}{v:.4f}")
    print(f"\n  Result: {'PASS' if report['passed'] else 'FAIL'}")
    print(f"{'='*60}\n")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="VibeVoice Voice Cloning Quality Report")
    parser.add_argument("--model", default="/mnt/nas/models/vibevoice/VibeVoice-1.5B",
                        help="Path to VibeVoice-1.5B checkpoint")
    parser.add_argument("--reference_audio", default=None,
                        help="Path to reference voice audio (WAV/MP3). "
                             "If not provided, the model generates one.")
    parser.add_argument("--ref_text", default=DEFAULT_REF_TEXT,
                        help="Text for auto-generating reference voice (used if "
                             "--reference_audio is not provided)")
    parser.add_argument("--target_text", default=DEFAULT_TARGET_TEXT,
                        help="Text to synthesise for the cloning comparison")
    parser.add_argument("--output_dir", default="./quality_output",
                        help="Directory to save audio files and JSON report")
    parser.add_argument("--device", default="cuda",
                        help="Inference device (cuda / cuda:0 / cpu)")
    parser.add_argument("--cfg_scale", type=float, default=3.0)
    parser.add_argument("--ddpm_steps", type=int, default=20)
    args = parser.parse_args()

    if not os.path.isdir(args.model):
        print(f"ERROR: Model path not found: {args.model}", file=sys.stderr)
        sys.exit(1)

    device = args.device
    if "cuda" in device and not torch.cuda.is_available():
        print("CUDA not available, falling back to CPU.")
        device = "cpu"

    os.makedirs(args.output_dir, exist_ok=True)

    # Load model
    model, processor = load_model_and_processor(args.model, device)

    # --- Step 1: Reference voice ---
    if args.reference_audio:
        print(f"\nLoading reference audio: {args.reference_audio}")
        ref_audio = load_audio(args.reference_audio)
        print(f"  Duration: {len(ref_audio)/SAMPLE_RATE:.1f}s")
    else:
        print(f"\nGenerating reference voice...")
        print(f"  Text: {args.ref_text[:80]}...")
        ref_audio = generate(model, processor, args.ref_text,
                             cfg_scale=args.cfg_scale, ddpm_steps=args.ddpm_steps,
                             device=device)
        if ref_audio is None:
            print("ERROR: Reference audio generation failed.", file=sys.stderr)
            sys.exit(1)
        save_audio(os.path.join(args.output_dir, "reference.wav"), ref_audio)

    # --- Step 2: Cloned output ---
    print(f"\nGenerating cloned output...")
    print(f"  Text: {args.target_text[:80]}...")
    cloned_audio = generate(model, processor, args.target_text,
                            voice_samples=[ref_audio],
                            cfg_scale=args.cfg_scale, ddpm_steps=args.ddpm_steps,
                            device=device)
    if cloned_audio is None:
        print("ERROR: Cloned audio generation failed.", file=sys.stderr)
        sys.exit(1)
    save_audio(os.path.join(args.output_dir, "cloned.wav"), cloned_audio)

    # --- Step 3: Baseline output ---
    print(f"\nGenerating baseline output (no voice reference)...")
    baseline_audio = generate(model, processor, args.target_text,
                              cfg_scale=args.cfg_scale, ddpm_steps=args.ddpm_steps,
                              device=device)
    if baseline_audio is None:
        print("ERROR: Baseline audio generation failed.", file=sys.stderr)
        sys.exit(1)
    save_audio(os.path.join(args.output_dir, "baseline.wav"), baseline_audio)

    # --- Step 4: Similarity report ---
    print("\nComputing speaker similarity metrics...")
    from vibevoice.eval import SpeakerSimilarity
    sim = SpeakerSimilarity(device=device)

    if not sim.ecapa_available:
        print("  Warning: ECAPA-TDNN not available. Using librosa features only.")

    report = sim.report(ref_audio, cloned_audio, baseline_audio, sr=SAMPLE_RATE)

    # Print and save
    print_report(report)
    report_path = os.path.join(args.output_dir, "quality_report.json")
    with open(report_path, "w") as f:
        json.dump(report, f, indent=2)
    print(f"  JSON report saved: {report_path}")

    sys.exit(0 if report["passed"] else 1)


if __name__ == "__main__":
    main()
